### PR TITLE
ecma6.json 

### PR DESCRIPTION
**Pull request by angelozerr**
This PR provides a first version of ecma6.json.

This def must be improved to support iterator (see TODO_ITERATOR).

I think too that TypedArray_ctor, Map_ctor, Set_ctor should be created and used too.

In other words this PR desribes the whole ES6 defined at https://developer.mozilla.org//en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla

This def must be improved to manage iterator and some !effect.

### CODE REVIEW

**Comment by marijnh** [comment]
Looks great. But shouldn't the `Promise` properties live under `Promise.prototype`?

**Comment by angelozerr** [comment]
> Looks great. But shouldn't the Promise properties live under Promise.prototype?

As I said you, it's not perfect and I think it should be improved, but it's a first step. I think we could improve it step by step. What do you think?

More I tell me if tern could customize acorn with 6 version when ecma6.json is loaded.

**Comment by marijnh** [comment]
I think it is safe to simply add support for ES6 syntax by default -- it is almost entirely backwards-compatible anyway. Acorn parses ES6 now, but before we turn that on in Tern we'll have to add support for new syntax constructs.

**Comment by marijnh** [comment]
So should the Promise properties be moved to `prototype`, or is there a reason they are directly on the constructor?

**Comment by angelozerr** [comment]
> So should the Promise properties be moved to prototype, or is there a reason they are directly on the constructor?

To be honnest with you, I don't know -( I have generated that from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by marijnh** [comment]
I've merged this as de4efe7df844ea357f08.

**Pull request closed without merging**
