### PR TITLE
Load external JSON Type Definition

### PR DESCRIPTION
**Pull request by angelozerr**
This PR gives the capability to load external JSON Type Definition hosted in a tern-{def} folder like tern plugin.

### CODE REVIEW

**Comment by marijnh** [comment]
Looks good. Could you update the manual to mention this feature?

**Comment by angelozerr** [comment]
@marijnh is there any chance that you accept this PR. I would like to use external JSON Type Definitions. Thanks!

**Comment by marijnh** [comment]
Merged. Please edit `doc/src/manual.txt` instead of `doc/manual.html` next time, since the latter is overwritten every time I run `make`, and your changes will be lost.

**Comment by angelozerr** [comment]
> Please edit doc/src/manual.txt instead of doc/manual.html next time,

Ooops I have not seen that, sorry -(

Thanks @marijnh !

**Pull request closed without merging**
