### PR TITLE
Completion for module specifiers

### PR DESCRIPTION
**Pull request by angelozerr**
This PR provides completion for module specifiers. It works only if you type one character in the specifier. Ex : 

```javascript
import {L // here Ctrl+space shows List} from "./list"
```

The completion returns `isSpecifier: true` In my case (tern.java), I need that because my completion provides "List" and "List(head, tail)" (it's helpfull for function, but not for specifier).

### CODE REVIEW

**Comment by marijnh** [comment]
Code related to `import` declarations does _not_ belong in the modules plugin, which is a generic piece of infrastructure for all kinds of module systems. I've pushed an alternative patch that uses the existing `isImport` functionality to do this in a module-system-independent way.

**Comment by angelozerr** [comment]
Thanks @marijnh for your patch whcih works well and thanks to have keeping isSpecifier: true.

I finnd it's just shame that it doesn't work when no word are typed (I have found a solution to do that).

**Comment by marijnh** [comment]
I looked at your code and didn't see anything to handle this situation. How did you detect that the cursor is in such a position?

**Comment by angelozerr** [comment]
Yes I know I had the same problem than you, I would like just tell you about this limitation and I hoped that you will find a solution, but I'm afraid that it is not possible.

**Comment by marijnh** [comment]
You could do your own custom superficial parse of the source text to figure out whether the position is between braces in an import, but for now I think that's too much complexity.

**Pull request closed without merging**
